### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_app.default.apps')

### ISSUE THREAD

**Issue by apysannew** [francktamala/LoginApp#1]
Please help I am constantly getting this error I am very new in react Native, Please help

TypeError: undefined is not an object (evaluating '_app.default.apps')

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer

**Comment by francktamala** [comment]
Which version of Firebase are you using ? I find version 8.2.3 to work best with Expo
